# app/crud.py
from sqlalchemy.orm import Session
from . import models, schemas

def create_loan_application(db: Session, application: schemas.LoanApplicationCreate):
    # 1. Create the database object using data from the schema
    db_application = models.LoanApplication(
        full_name=application.full_name,
        income=application.income,
        loan_amount=application.loan_amount,
        credit_score=application.credit_score,
        status="PENDING" # Default status
    )
    
    # 2. Add to the session (The Staging Area)
    db.add(db_application)
    
    # 3. Commit (Save to Disk)
    db.commit()
    
    # 4. Refresh (Get the ID and Created_At generated by the DB)
    db.refresh(db_application)
    
    return db_application

# --- USER CRUD ---
from . import auth_utils

def get_user_by_email(db: Session, email: str):
    return db.query(models.User).filter(models.User.email == email).first()

def create_user(db: Session, user: schemas.UserCreate):
    hashed_password = auth_utils.get_password_hash(user.password)
    db_user = models.User(
        email=user.email, 
        hashed_password=hashed_password,
        full_name=user.full_name
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

def authenticate_user(db: Session, email: str, password: str):
    user = get_user_by_email(db, email)
    if not user:
        return False
    if not auth_utils.verify_password(password, user.hashed_password):
        return False
    return user

# --- HISTORY CRUD ---
def create_history_entry(db: Session, history: schemas.RiskAnalysisHistoryCreate):
    db_history = models.RiskAnalysisHistory(
        user_id=history.user_id,
        filename=history.filename,
        result=history.result
    )
    db.add(db_history)
    db.commit()
    db.refresh(db_history)
    return db_history

def get_user_history(db: Session, user_id: int):
    return db.query(models.RiskAnalysisHistory).filter(models.RiskAnalysisHistory.user_id == user_id).order_by(models.RiskAnalysisHistory.created_at.desc()).all()